name: build-cv

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex
          latexmk_use_xelatex: true
          extra_system_packages: "fontconfig"
          pre_compile: |
            tlmgr update --self || true
            tlmgr install latexmk xetex fontspec fontawesome5 pgf
          output_directory: dist
          output_file: vicent-perez-cv.pdf
          continue_on_error: false

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: vicent-perez-cv
          path: dist/vicent-perez-cv.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: vicent-perez-cv
          path: dist/
